/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 * 
 * @license 
 * This file is part of <?=$extension?> check the LICENSE file for information.
 * 
 * @note
 * This file is auto-generated by PEG.
*/

#ifndef <?=$header_define?>_CLASSES_GUARD
#define <?=$header_define?>_CLASSES_GUARD

#include "common.h"
#include "references.h"
#include "<?=$header_name?>"

