/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 *
 * @license
 * This file is part of <?=$extension?> check the LICENSE file for information.
 *
 * @note
 * This file is auto-generated by PEG.
*/

#include "<?=$php_header_name?>"
#include "<?=$header_name?>"
#include "enums.h"

