/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 *
 * @license
 * This file is part of <?=$extension?> check the LICENSE file for information.
 *
 * @description
 * File that can be used to include all headers generated by PEG.
 *
 * @note
 * This file is auto-generated by PEG.
*/

#ifndef <?=strtoupper($extension)?>_ALL_HEADERS_H_GUARD
#define <?=strtoupper($extension)?>_ALL_HEADERS_H_GUARD

<?=$headers?>

#endif //<?=strtoupper($extension)?>_ALL_HEADERS_H_GUARD
