/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 * 
 * @license 
 * This file is part of <?=$extension?> check the LICENSE file for information.
 *
 * @description
 * File that holds some helper functions used by the extension.
 * 
 * @note
 * This file is auto-generated by PEG.
*/

#ifndef <?=strtoupper($extension)?>_FUNCTIONS_H_GUARD
#define <?=strtoupper($extension)?>_FUNCTIONS_H_GUARD

#include "common.h"

BEGIN_EXTERN_C()

/**
 * Custom function to register objects as constants
 */
#define <?=strtoupper($extension)?>_REGISTER_OBJECT_CONSTANT(name, object, flags) \
<?=$extension?>_register_object_constant((name), sizeof(name), (object), (flags), module_number TSRMLS_CC)

void <?=strtolower($extension)?>_register_object_constant(
    const char *name, 
    uint name_len, 
    zval object, 
    int flags, 
    int module_number 
    TSRMLS_DC
);

/**
 * Custom zend_method_call function to call methods with more than 2 parameters
 */
int <?=strtolower($extension)?>_call_method(
    zval **object_pp, 
    zend_class_entry *obj_ce, 
    zend_function **fn_proxy, 
    const char *function_name, 
    int function_name_len, 
    zval **retval_ptr_ptr, 
    int param_count, 
    zval*** params 
    TSRMLS_DC
);

END_EXTERN_C()


#endif //<?=strtoupper($extension)?>_FUNCTIONS_H_GUARD
