/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 * 
 * @license 
 * This file is part of <?=$extension?> check the LICENSE file for information.
 * 
 * @note
 * This file is auto-generated by PEG.
*/

#ifndef <?=$header_define?> 
#define <?=$header_define?>

#include "common.h"

BEGIN_EXTERN_C()

