/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 *
 * @license
 * This file is part of <?=$extension?> check the LICENSE file for information.
 *
 * @note
 * This file is auto-generated by PEG.
*/

#ifndef <?=strtoupper($extension)?>_COMMON_H_GUARD
#define <?=strtoupper($extension)?>_COMMON_H_GUARD

#ifdef PHP_WIN32
    /* For disabling warnings about unreferenced local variable */
    #pragma warning (disable : 4101)
    #pragma warning (disable : 4102)
    #pragma warning (disable : 4700)

    /* Disable forcing zend_bool to bool warnings */
    #pragma warning (disable : 4800)
#endif

/* Include PHP Standard Headers */
extern "C" {

/*
 * Import configure options when building outside
 * of the PHP source tree
 */
#ifdef HAVE_CONFIG_H
    #include "config.h"
#endif

#ifdef WORDS_BIGENDIAN
    #undef WORDS_BIGENDIAN
#endif

#ifdef M_PI
    #undef M_PI
#endif

#ifdef _WIN32_WINNT
    #undef _WIN32_WINNT
#endif

#include "php.h"
#include "zend.h"
#include "zend_API.h" //Declaration for zend_declare_class_constant_long
#include "ext/standard/info.h" //Declaration of ini functions like php_info_print_table_start()

/*
 * For backward compatibility with older versions of php
 * that did not implemented this macro.
 */
#ifndef PHP_FE_END
    #define PHP_FE_END {NULL, NULL, NULL}
#endif

}

#endif //<?=strtoupper($extension)?>_COMMON_H_GUARD
