/*
 * @author <?=$authors?>
 * @contributors <?=$contributors?>
 * 
 * @license 
 * This file is part of <?=$extension?> check the LICENSE file for information.
 *
 * @description
 * File that holds the function prototypes of the extension
 * 
 * @note
 * This file is auto-generated by PEG.
*/

#ifndef <?=strtoupper($extension)?>_FUNCTIONS_H_GUARD
#define <?=strtoupper($extension)?>_FUNCTIONS_H_GUARD

/**
 * Space reserved for the autogenerated function prototypes
 */
<?=$function_prototypes?>


#endif //<?=strtoupper($extension)?>_FUNCTIONS_H_GUARD
