/*
 * @author <?=$authors?> 
 * @contributors <?=$contributors?> 
 * 
 * @license 
 * This file is part of <?=$extension?> check the LICENSE file for information.
 * 
 * @description
 * File that stores all types of classes used to check if an object 
 * passed to a method or function is castable to another type by
 * inheritance.
 * 
 * @note
 * This file is auto-generated by PEG.
 * 
*/

#ifndef <?=strtoupper($extension)?>_OBJECT_TYPES_H_GUARD
#define <?=strtoupper($extension)?>_OBJECT_TYPES_H_GUARD

enum <?=strtolower($extension)?>_object_type
{
    <?=$object_types?>
};

typdef struct _php_<?=strtolower($extension)?>_zo
{
    zend_object zo;
    void* native_object;
    <?=strtolower($extension)?>_object_type object_type;
    int is_user_initialized;
} php_<?=strtolower($extension)?>_zo;

#endif //<?=strtoupper($extension)?>_OBJECT_TYPES_H_GUARD
