#!/bin/bash

# Example of how to run peg as a normal cli application on unix 
# environments by using a shell script. You can place this file on
# your /home/user/bin directory.

# Set to the path where you have peg installed
MAIN_PATH="/usr/lib/peg"

# Executes peg with environment variables that point to the paths 
# needed for its correct functioning.
PEG_SKELETON_PATH="${MAIN_PATH}/skeleton" \
PEG_LIBRARY_PATH="${MAIN_PATH}/" \
PEG_LOCALE_PATH="${MAIN_PATH}/locale" \
php $MAIN_PATH/main.php $@
