/*
 * @author <?=$authors?>
 * @contributors <?=$contributors?>
 * 
 * @license 
 * This file is part of <?=$extension?> check the LICENSE file for information.
 *
 * @description
 * File that holds the functions code of the extension
 * 
 * @note
 * This file is auto-generated by PEG.
*/

#include "php_<?=$extension?>.h"
#include "functions.h"

/**
 * Space reserved for autogenerated header includes
 */
<?=$header_files?>

/**
 * Space reserved for autogenerated functions
 */
 
<?=$functions?>
